export const VWaterPaths = {
  login: `/login`,
  register: "/register",
  logout: `/logout`,
  home: `/home`,
  booking_water: "/book-water",
  profile: `/profile`,
  order: `/order`,
  faucet1920L: "/faucet-19l-20l",
  facedown1920L: "/facedown-19l-20l",
  bottle350ml: "/bottle-350ml",
  bottle500ml: "/bottle-500ml",
  product: "/product",
  cart: "/cart",
  cart_reOrder: "/cart?reorder=true",
  orderTracking: "/order-tracking",
  historyTransaction: "/history-transaction",
};
